/*
 *  Ray Cloud Browser: interactively skim processed genomics data with energy
 *  Copyright (C) 2012, 2013  Sébastien Boisvert
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, version 3 of the License.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "PathHelper.h"

#include <storage/PathDatabase.h>

#include <iostream>
using namespace std;

#include <stdio.h>
#include <stdlib.h>

/**
 * Create a path database.
 * \author Sébastien Boisvert
 */
int PathHelper::call(int argc,char**argv){

	if(argc!=3){
		cout<<"Create a read-only index on a fasta file, usually Contigs.fasta generated by the Ray assembler"<<endl;

		cout<<endl;

		cout<<"Usage: "<<PROGRAM_NAME<<" "<<argv[0]<<" Contigs.fasta Contigs.dat"<<endl;
		cout<<endl;

		return 0;
	}

	const char*file=argv[1];
	const char*output=argv[2];

	PathDatabase mock;

	mock.index(file,output);

	return EXIT_SUCCESS;
}
